import path from "node:path";

/** Base dir shared with the worker. Matches simulation/src/engine/paths.ts. */
export function simDataDir(): string {
  return process.env.SIM_DATA_DIR || process.cwd();
}

/**
 * SQLite file holding the portal's simulation records, run-state, event
 * scripts, and form-webhook registry. The portal and the (separately spawned)
 * worker both resolve the same path so they read/write one database. Defaults
 * to `<SIM_DATA_DIR>/data/simulations.sqlite`; override with `PORTAL_DB_FILE`
 * to point at a persistent, writable volume in ephemeral-host deployments.
 * Must stay in step with simulation/src/engine/paths.ts.
 */
export function simDbPath(): string {
  return (
    process.env.PORTAL_DB_FILE ||
    path.join(simDataDir(), "data", "simulations.sqlite")
  );
}

/**
 * Where event scripts were written before they moved into the database. Read
 * only, so a run generated by an older build stays runnable on a host where its
 * file survives; nothing writes here any more. `SIM_DATA_DIR` defaults to the
 * portal's working directory, which on a container host is wiped by every
 * redeploy — which is precisely why scripts left.
 */
export function eventsFilePath(id: string): string {
  return path.join(simDataDir(), ".simulations", `${id}.events.json`);
}

/** Pre-database sidecar for {@link eventsFilePath}'s generation summary. */
export function generationFilePath(id: string): string {
  return path.join(simDataDir(), ".simulations", `${id}.generation.json`);
}

/** Worker log for a simulation. The portal tees the spawned worker's stdout and
 * stderr here so a run's progress is inspectable after the fact. */
export function logFilePath(id: string): string {
  return path.join(simDataDir(), ".simulations", `${id}.log`);
}
