import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import type { SimulationEvent } from "./events";
import type { GenerationSummary } from "./script";

const EVENTS: SimulationEvent[] = [
  {
    id: "e1",
    scheduledMicros: 1000,
    targetKey: "marriage-registration",
    targetUrl: null,
    payload: { a: 1 },
  },
];

const SUMMARY: GenerationSummary = {
  generatedAt: "2026-01-01T00:00:00.000Z",
  citizens: 3,
  programs: 1,
  days: 2,
  events: 1,
  unroutedTargets: ["marriage-registration"],
  unroutedEvents: 1,
};

let dir: string;
const origDbFile = process.env.PORTAL_DB_FILE;
const origSimDataDir = process.env.SIM_DATA_DIR;

// The db module caches its connection in module state, so each test gets a fresh
// database file and a fresh module registry.
beforeEach(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), "sim-script-"));
  process.env.PORTAL_DB_FILE = path.join(dir, "test.sqlite");
  process.env.SIM_DATA_DIR = dir;
  vi.resetModules();
});

afterEach(async () => {
  if (origDbFile === undefined) delete process.env.PORTAL_DB_FILE;
  else process.env.PORTAL_DB_FILE = origDbFile;
  if (origSimDataDir === undefined) delete process.env.SIM_DATA_DIR;
  else process.env.SIM_DATA_DIR = origSimDataDir;
  await fs.rm(dir, { recursive: true, force: true });
});

async function loadScript() {
  return import("./script");
}

/** Write the files scripts were stored in before they moved into the database. */
async function writeLegacyFiles(
  id: string,
  events: SimulationEvent[],
  summary?: GenerationSummary,
): Promise<void> {
  const { eventsFilePath, generationFilePath } = await import("./paths");
  await fs.mkdir(path.dirname(eventsFilePath(id)), { recursive: true });
  await fs.writeFile(eventsFilePath(id), JSON.stringify(events));
  if (summary) {
    await fs.writeFile(generationFilePath(id), JSON.stringify(summary));
  }
}

describe("readScript", () => {
  it("round-trips the events and summary written together", async () => {
    const script = await loadScript();
    await script.writeScript("sim-1", EVENTS, SUMMARY);

    expect(await script.readScript("sim-1")).toEqual({
      events: EVENTS,
      generation: SUMMARY,
    });
  });

  it("replaces a previous script when a simulation is generated again", async () => {
    const script = await loadScript();
    await script.writeScript("sim-1", EVENTS, SUMMARY);
    await script.writeScript("sim-1", [], null);

    expect(await script.readScript("sim-1")).toEqual({
      events: [],
      generation: null,
    });
  });

  it("returns null when the simulation has no script", async () => {
    const script = await loadScript();
    expect(await script.readScript("missing")).toBeNull();
    expect(await script.hasScript("missing")).toBe(false);
    expect(await script.readEvents("missing")).toEqual([]);
  });

  // A script that generated no events is runnable and self-explaining; one that
  // doesn't exist is neither. The two must not read the same.
  it("distinguishes an empty script from no script", async () => {
    const script = await loadScript();
    await script.writeScript("empty", [], SUMMARY);

    expect(await script.hasScript("empty")).toBe(true);
    expect(await script.readEvents("empty")).toEqual([]);
    expect((await script.readScript("empty"))?.generation).toEqual(SUMMARY);
  });

  // Upgrading shouldn't strand a run generated by the previous build whose files
  // are still on this host.
  it("falls back to the pre-database files", async () => {
    const script = await loadScript();
    await writeLegacyFiles("legacy", EVENTS, SUMMARY);

    expect(await script.readScript("legacy")).toEqual({
      events: EVENTS,
      generation: SUMMARY,
    });
  });

  it("reads a pre-database script whose summary sidecar is absent", async () => {
    const script = await loadScript();
    await writeLegacyFiles("legacy-no-summary", EVENTS);

    expect(await script.readScript("legacy-no-summary")).toEqual({
      events: EVENTS,
      generation: null,
    });
  });

  it("prefers the stored script over a stale file of the same id", async () => {
    const script = await loadScript();
    await writeLegacyFiles("both", EVENTS, SUMMARY);
    await script.writeScript("both", [], null);

    expect(await script.readScript("both")).toEqual({
      events: [],
      generation: null,
    });
  });
});

describe("deleteScript", () => {
  it("removes the stored script and any pre-database files", async () => {
    const script = await loadScript();
    const { eventsFilePath } = await import("./paths");
    await script.writeScript("gone", EVENTS, SUMMARY);
    await writeLegacyFiles("gone", EVENTS, SUMMARY);

    await script.deleteScript("gone");

    expect(await script.readScript("gone")).toBeNull();
    await expect(fs.access(eventsFilePath("gone"))).rejects.toThrow();
  });
});
