import { promises as fs } from "node:fs";
import { eq } from "drizzle-orm";
import { getDb, simulationScripts } from "./db.js";
import { eventsFilePath } from "./paths.js";

export interface SimulationEvent {
  id: string;
  scheduledMicros: number;
  targetKey: string;
  targetUrl: string | null;
  payload: unknown;
}

/**
 * Shown when a simulation has no event script to run. Matches the portal's
 * MISSING_SCRIPT_MESSAGE (portal/src/lib/simulations/store.ts): the portal
 * normally refuses to start such a run, so a worker only reaches this if the
 * script vanished between the two — but it is what the run page displays, so it
 * has to name the way out rather than a filename.
 */
export const MISSING_SCRIPT_MESSAGE =
  "This simulation has no event script to run. Generate it again, then start it.";

/**
 * Load the precomputed events for a simulation from the database the portal
 * generated them into — the same volume as the record, so a redeploy can no
 * longer leave a `generated` simulation with nothing to run. Falls back to the
 * pre-database file for a run generated by an older build whose file is still
 * on this host. Throws when there is no script either way.
 */
export async function readEvents(id: string): Promise<SimulationEvent[]> {
  const row = getDb()
    .select()
    .from(simulationScripts)
    .where(eq(simulationScripts.simulation_id, id))
    .get();

  const raw = row ? row.events : await readLegacyEventsFile(id);
  if (raw === null) throw new Error(MISSING_SCRIPT_MESSAGE);

  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error(`Event script for ${id} is not an array`);
  }
  return parsed as SimulationEvent[];
}

/** The pre-database events file's contents, or null when it isn't there. */
async function readLegacyEventsFile(id: string): Promise<string | null> {
  try {
    return await fs.readFile(eventsFilePath(id), "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
}
