import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

let dir: string;

beforeEach(async () => {
  dir = await fs.mkdtemp(path.join(os.tmpdir(), "sim-engine-"));
  process.env.SIM_DATA_DIR = dir;
  delete process.env.PORTAL_DB_FILE;
  vi.resetModules();
});
afterEach(async () => {
  delete process.env.SIM_DATA_DIR;
  await fs.rm(dir, { recursive: true, force: true });
});

/**
 * Path helpers only. These are pure, and resolving one must not open (or create
 * a directory for) the database it names — a path assertion has to be able to
 * name a location this process can't write to.
 */
async function loadPaths() {
  return import("./paths.js");
}

/** Fresh modules per test, so each gets its own database in its own tempdir. */
async function load() {
  const [events, paths, db] = await Promise.all([
    import("./events.js"),
    import("./paths.js"),
    import("./db.js"),
  ]);
  return { ...events, ...paths, db: db.getDb(), scripts: db.simulationScripts };
}

describe("paths", () => {
  it("resolves the shared sqlite db under data/ in SIM_DATA_DIR", async () => {
    const { simDbPath } = await loadPaths();
    expect(simDbPath()).toBe(path.join(dir, "data", "simulations.sqlite"));
  });

  it("honours PORTAL_DB_FILE as an explicit override", async () => {
    process.env.PORTAL_DB_FILE = "/mnt/vol/portal.sqlite";
    const { simDbPath } = await loadPaths();
    expect(simDbPath()).toBe("/mnt/vol/portal.sqlite");
    delete process.env.PORTAL_DB_FILE;
  });

  it("resolves the pre-database events file under .simulations", async () => {
    const { eventsFilePath } = await loadPaths();
    expect(eventsFilePath("abc")).toBe(
      path.join(dir, ".simulations", "abc.events.json"),
    );
  });
});

describe("readEvents", () => {
  it("reads the script the portal stored in the shared database", async () => {
    const { readEvents, db, scripts } = await load();
    db.insert(scripts)
      .values({
        simulation_id: "abc",
        events: JSON.stringify([
          { id: "e1", scheduledMicros: 0, targetKey: "national-id", targetUrl: null, payload: {} },
        ]),
        generation: null,
        updated_at: "t0",
      })
      .run();

    const events = await readEvents("abc");
    expect(events).toHaveLength(1);
    expect(events[0].id).toBe("e1");
  });

  // A run generated by a build that still wrote files stays runnable, as long as
  // the file survived on this host.
  it("falls back to the pre-database events file", async () => {
    const { readEvents, eventsFilePath } = await load();
    await fs.mkdir(path.join(dir, ".simulations"), { recursive: true });
    await fs.writeFile(
      eventsFilePath("legacy"),
      JSON.stringify([
        { id: "e1", scheduledMicros: 0, targetKey: "national-id", targetUrl: null, payload: {} },
      ]),
    );

    expect(await readEvents("legacy")).toHaveLength(1);
  });

  it("reads a stored script that generated no events", async () => {
    const { readEvents, db, scripts } = await load();
    db.insert(scripts)
      .values({ simulation_id: "empty", events: "[]", generation: null, updated_at: "t0" })
      .run();

    expect(await readEvents("empty")).toEqual([]);
  });

  // What the run page shows if a script ever does go missing — so it has to name
  // the way out, not a filename.
  it("fails with an actionable message when there is no script", async () => {
    const { readEvents, MISSING_SCRIPT_MESSAGE } = await load();
    await expect(readEvents("missing")).rejects.toThrow(MISSING_SCRIPT_MESSAGE);
    expect(MISSING_SCRIPT_MESSAGE).not.toMatch(/ENOENT/);
  });
});
